# Generated by Django 2.2.9 on 2020-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='created_at',
            field=models.DateTimeField(verbose_name='Feb 01 2020 16:30:22'),
        ),
    ]
