# Generated by Django 2.2.9 on 2020-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_auto_20200201_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='created_at',
            field=models.DateTimeField(verbose_name='Feb 02 2020 06:31:10'),
        ),
    ]
