# Generated by Django 2.2.9 on 2020-02-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20200202_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
